SeoPositionBundle:
    resource: "@SeoPositionBundle/Controller/"
    type:     annotation
    prefix:   /

SeoCoreBundle:
    resource: "@SeoCoreBundle/Controller/"
    type:     annotation
    prefix:   /

SeoPageBundle:
    resource: "@SeoPageBundle/Controller/"
    type:     annotation
    prefix:   /

SeoUserBundle:
    resource: "@SeoUserBundle/Controller/"
    type:     annotation
    prefix:   /

homepage:
    pattern:   /
    defaults:  { _controller: SeoPageBundle:Page:index }

# FOS User Bundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
